FROM ghcr.io/graalvm/native-image-community:25 AS builder

ADD . /spring-native-demo
WORKDIR /spring-native-demo

RUN microdnf install -y maven && microdnf clean all

RUN ./mvnw clean package -Pnative --no-transfer-progress

FROM oraclelinux:10-slim

COPY --from=builder "spring-native-demo/target/spring-native-demo" spring-native-demo

CMD [ "sh", "-c", "./spring-native-demo"]